# Generated by Django 2.1.5 on 2019-01-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_s3', models.IntegerField()),
                ('day_s3', models.IntegerField()),
                ('boarding_s5', models.IntegerField()),
                ('day_s5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('has_olevel', models.BooleanField()),
                ('has_alevel', models.BooleanField()),
                ('has_boarding', models.BooleanField()),
                ('has_day', models.BooleanField()),
                ('has_female', models.BooleanField()),
                ('has_male', models.BooleanField()),
                ('num_students', models.IntegerField()),
                ('num_teachers', models.IntegerField()),
                ('location', models.CharField(choices=[('urban', 'URBAN'), ('rural', 'RURAL'), ('peri-urban', 'PERI-URBAN')], max_length=11)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('community_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='main.CommunityUnit')),
            ],
            options={
                'ordering': ('date_enrolled',),
            },
        ),
        migrations.AddField(
            model_name='feesstructure',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='main.School'),
        ),
    ]
