# Generated by Django 2.1.5 on 2019-01-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityunit',
            options={'ordering': ('name',)},
        ),
    ]
