# Generated by Django 2.1.5 on 2019-01-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190122_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('csv', models.FileField(upload_to='')),
            ],
        ),
    ]
