# Generated by Django 2.1.5 on 2019-01-23 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_datacsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacsv',
            name='name',
        ),
        migrations.AddField(
            model_name='datacsv',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
